# yaml-language-server: $schema=https://goreleaser.com/static/schema.json

version: 2
project_name: "vercel-scripts"
builds:
  - builder: "deno"
    binary: "vss"
    main: "src/main.ts"
    flags:
      - "--allow-all"
      - "--include=src/scripts"
      - "--include=src/runtime"
    targets:
      - "aarch64-apple-darwin"

homebrew_casks:
  - binary: "vss"
    description: "A powerful Deno-based CLI tool for managing Vercel and Next.js development workflows through an interactive collection of reusable scripts."
    dependencies:
      - formula: "jq"
    repository:
      owner: "wyattjoh"
      name: "homebrew-stable"

notarize:
  macos:
    - enabled: '{{ isEnvSet "MACOS_SIGN_P12" }}'
      sign:
        certificate: "{{ .Env.MACOS_SIGN_P12 }}"
        password: "{{ .Env.MACOS_SIGN_PASSWORD }}"
      notarize:
        issuer_id: "{{ .Env.MACOS_NOTARY_ISSUER_ID }}"
        key_id: "{{ .Env.MACOS_NOTARY_KEY_ID }}"
        key: "{{ .Env.MACOS_NOTARY_KEY }}"
        wait: true
        timeout: 20m
