name: Publish to JSR and Homebrew

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # Required for OIDC authentication with JSR

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Check formatting
        run: deno fmt --check

      - name: Lint code
        run: deno lint

      - name: Type check
        run: deno check

      - name: Checkout tap repository
        uses: actions/checkout@v4
        with:
          repository: wyattjoh/homebrew-stable
          token: ${{ secrets.GORELEASER_GITHUB_TOKEN }}
          path: homebrew-stable

      - name: Update Homebrew formula
        run: |
          # Extract version from tag
          NEW_VERSION=${GITHUB_REF#refs/tags/v}
          NEW_TAG=${GITHUB_REF#refs/tags/}

          cd homebrew-stable

          # Get the current commit SHA for the new tag
          NEW_REVISION=$(git ls-remote https://github.com/wyattjoh/vercel-scripts.git refs/tags/${NEW_TAG} | cut -f1)

          # Update the formula file
          sed -i.bak "s/tag:      \".*\"/tag:      \"${NEW_TAG}\"/" Formula/vercel-scripts.rb
          sed -i.bak "s/revision: \".*\"/revision: \"${NEW_REVISION}\"/" Formula/vercel-scripts.rb
          rm Formula/vercel-scripts.rb.bak

          # Configure git and commit
          git config user.name "Wyatt Johnson"
          git config user.email "me@wyattjoh.ca"
          git add Formula/vercel-scripts.rb
          git commit -m "vercel-scripts: update to ${NEW_TAG}"
          git push

      - name: Publish packages to JSR
        run: deno publish
